### Your name:

<pre> Derek Pyne </pre>

### Collaborators:

<pre> None </pre>


In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Markdown referece can be found here:
    http://nestacms.com/docs/creating-content/markdown-cheat-sheet

Q1. Why would it be a problem if our training set and test set are the same.

Using the same test and training set poses two big problems. First, by exposing our model to all our data, there is a high risk that the model will overfit the data if it has the capability to do so. Secondly, it leaves us without an estimate of how our model will perform in the real world since an estimate of the performance is performed on the same data used to train the model (making it a bias estimate).

Q2 [OPTIONAL]. Explain step by step the process to select k in the k-nearest neighbor algorithm (pseudocode) 

- Calculate distance from p to every observation in training set
- Sort distances
- Select k closest distances
- Average observation value at k closest distances

Q3. For the k-nearest regression. What happends when k = n. Where n is equal to the training size.

When k=n we will always select all points no matter what the input value. This means that the result will always be the total average of our training set no matter what point we are evaluating our model with.

Q4. Define a function that takes a 1-d numpy array, a parameter k, and a number p.
The function returns an estimate equal to the mean of the closest k points to the number p

In [2]:
def k_neighbor(input_data, k, p):
    """Returns the k-neighbor estimate for p using data input_data.
    
    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    
    If you make assumptions please explain them in the comments. i.e. tie breaking strategy.
    """
    
    abs_distance = np.abs(input_data - p)
    
    closest_point_index = np.argsort(abs_distance)
    
    return np.mean(input_data[closest_point_index[:k]])

In [3]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor(input_data=data, k=3, p=5))
print(k_neighbor(input_data=data, k=2, p=15))
print(k_neighbor(input_data=data, k=3, p=25))
print(k_neighbor(input_data=data, k=1, p=55))
print(k_neighbor(input_data=data, k=3, p=55))
print(k_neighbor(input_data=data, k=10, p=55))

4.0
14.0
26.0
40.0
31.3333333333
19.6


In [4]:
#Enter your observations and comments here


To break ties when selecting the k-nearest observations, the first points in the sorted distance array was used. Since we are using `numpy.argsort` it defaults to using quicksort which appears to break ties based on which point occured first in the array (example below).

We can also see that as k is larger, the estimate moves closer to the mean and takes less influence from point p. The last three evaluations show this which have a fixed p of 55 and as k increases the estimate lowers towards the mean (which in this case is probably a worse estimate).

In [5]:
print('Checking np.argsort tie breaking:')
np.argsort([1,1,1,1,2,0,0,0])

Checking np.argsort tie breaking:


array([5, 6, 7, 0, 1, 2, 3, 4])

Q5. Similar to Q4 but for the n dimentional case. 

In [6]:
def l1_norm(a,b):
    """Returns the l1 norm (a,b)"""
    return sum(np.abs(a-b))
    
def l2_norm(a,b):
    """Returns the l2 norm (a,b)""" 
    return np.linalg.norm(a-b)
    
def k_neighbor_nd(input_data, k, p, metric='l1', mode='mean'):
    """Returns the k-neighbor estimate for p using data input_data.

    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    metric -- l1 or l2. l1 norm or l2 norm https://en.wikipedia.org/wiki/Norm_(mathematics)
    mode -- estimator possible values = 'mean', 'median', 'max'
    
    Implement the l1 and l2 norms
    for mean, median and max, use np.mean, np.median and np.max
    """
    metrics = {
        'l1': l1_norm,
        'l2': l2_norm
    }
    distance = [metrics[metric](x, p) for x in input_data]
    
    closest_point_index = np.argsort(distance)

    modes = {
        'mean': np.mean,
        'median': np.median,
        'max': np.max
    }

    return modes[mode](input_data[closest_point_index[:k]], axis=0)
    

In [7]:
data_4d = np.array([[4, 1, 2, 1], [1, 4, 2, 0], [3, 3, 1, 1], 
        [4, 0, 0, 0], [1, 2, 0, 0], [3, 4, 2, 3], 
        [2, 4, 4, 2], [2, 1, 4, 1], [3, 3, 2, 4], 
        [4, 3, 0, 4], [2, 2, 4, 0],[4, 3, 0, 2], 
        [4, 3, 0, 2], [0, 3, 4, 2]])

In [8]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l1', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l1', mode='median'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l2', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l2', mode='median'))

[ 2.          2.33333333  4.          1.        ]
[ 4.  3.  0.  2.]
[4 4 2 4]
[ 3.  3.  2.  4.]
[ 3.  4.  2.  3.]
[ 1.33333333  2.66666667  4.          1.66666667]
[ 3.5  3.   0.5  1.5]
[4 4 2 4]
[ 3.  3.  2.  4.]
[ 3.  4.  2.  3.]


We can see that the l1 norm penalizes single dimensions that differ more then the l2 norm which looks more at the overall closeness between point p and each vector in the input data. In other words, if p is identical to a vector in the input data except for one dimension, the l1 norm will punish this more then the l2 norm.


Q6[Optional]. Read the documentation on KNeighborsRegressor

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
    
Explore the source code:
    https://github.com/scikit-learn/scikit-learn/blob/ef5cb84a/sklearn/neighbors/regression.py
        
How different it is from your implementation? How well can you follow the code? Did you learn something new?

A couple of observations about the SK-Learn implementation that differ from mine:
- In our case, we return a point/vector that is as close as possible to the input p. In other words, we return something of the same shape as the input data. In the SK-Learn implementation there is an input matrix X and an output vector Y. Inputs are made in the dimension of X to make a prediction for Y
- Arrays are preallocated for speed.
- Weights can be provided to convey the importance of points in the input data